/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_demo_jniTest_JniTest */

#ifndef _Included_com_example_demo_jniTest_JniTest
#define _Included_com_example_demo_jniTest_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_demo_jniTest_JniTest
 * Method:    callCppMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_demo_jniTest_JniTest_callCppMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
